import { deepFreeze } from "../model/limits.js";
import type {
  CardPresetId,
  PresentationDescriptor,
  PresentationStatus,
  TextStyle,
} from "../model/types.js";

// Owned slot/typography metadata. Decorative geometry stays in the SVG renderer.
const definitions: readonly Omit<
  PresentationDescriptor,
  "parameters" | "accentGeometry" | "status"
>[] = [
  {
    id: "buildReceipt",
    profile: "buildReceipt/v1",
    name: "Build Receipt",
    group: "Useful",
    accent: "#32816b",
    background: "#111c19",
    rows: [1, 3, 5, 5, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#65716d",
          fontSize: 11.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 36.0,
        y: 36.0,
        anchor: "start",
        safeWidth: 475,
        maxCodePoints: 80,
      },
      {
        id: "project",
        line: 1,
        run: 0,
        label: "Project",
        style: {
          color: "#1c2a26",
          fontSize: 32.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 36.0,
        y: 81.0,
        anchor: "start",
        safeWidth: 480,
        maxCodePoints: 48,
      },
      {
        id: "outcome",
        line: 1,
        run: 2,
        label: "Outcome",
        style: {
          color: "#156751",
          fontSize: 12.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 568.0,
        y: 61.0,
        anchor: "start",
        safeWidth: 88,
        maxCodePoints: 80,
        values: ["PASSED", "FAILED", "WARNING", "UNKNOWN"],
      },
      {
        id: "revisionLabel",
        line: 2,
        run: 0,
        label: "Revision label",
        style: {
          color: "#63736c",
          fontSize: 11.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 36.0,
        y: 132.0,
        anchor: "start",
        safeWidth: 170,
        maxCodePoints: 80,
      },
      {
        id: "durationLabel",
        line: 2,
        run: 2,
        label: "Duration label",
        style: {
          color: "#63736c",
          fontSize: 11.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 237.0,
        y: 132.0,
        anchor: "start",
        safeWidth: 170,
        maxCodePoints: 80,
      },
      {
        id: "checksLabel",
        line: 2,
        run: 4,
        label: "Checks label",
        style: {
          color: "#63736c",
          fontSize: 11.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 438.0,
        y: 132.0,
        anchor: "start",
        safeWidth: 200,
        maxCodePoints: 80,
      },
      {
        id: "revision",
        line: 3,
        run: 0,
        label: "Revision",
        style: {
          color: "#263831",
          fontSize: 21.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 36.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 170,
        maxCodePoints: 80,
      },
      {
        id: "duration",
        line: 3,
        run: 2,
        label: "Duration",
        style: {
          color: "#263831",
          fontSize: 21.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 237.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 170,
        maxCodePoints: 80,
      },
      {
        id: "checks",
        line: 3,
        run: 4,
        label: "Checks",
        style: {
          color: "#263831",
          fontSize: 21.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 438.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 200,
        maxCodePoints: 80,
      },
      {
        id: "environment",
        line: 4,
        run: 0,
        label: "Environment",
        style: {
          color: "#50675e",
          fontSize: 11.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 36.0,
        y: 214.0,
        anchor: "start",
        safeWidth: 320,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 5,
        run: 0,
        label: "Footer",
        style: {
          color: "#50675e",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 654.0,
        y: 214.0,
        anchor: "end",
        safeWidth: 255,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "requestTrace",
    profile: "requestTrace/v1",
    name: "Request Trace",
    group: "Useful",
    accent: "#66c6c7",
    background: "#141e26",
    rows: [1, 7, 5, 5, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#8a9ca7",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 32.0,
        y: 31.0,
        anchor: "start",
        safeWidth: 480,
        maxCodePoints: 80,
      },
      {
        id: "method",
        line: 1,
        run: 0,
        label: "Method",
        style: {
          color: "#58d4d5",
          fontSize: 25.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 72.0,
        anchor: "start",
        safeWidth: 54,
        maxCodePoints: 80,
      },
      {
        id: "path",
        line: 1,
        run: 2,
        label: "Path",
        style: {
          color: "#edf3f6",
          fontSize: 25.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 98.0,
        y: 72.0,
        anchor: "start",
        safeWidth: 370,
        maxCodePoints: 80,
      },
      {
        id: "status",
        line: 1,
        run: 4,
        label: "Status",
        style: {
          color: "#b8e1cd",
          fontSize: 11.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 648.0,
        y: 32.0,
        anchor: "end",
        safeWidth: 92,
        maxCodePoints: 80,
      },
      {
        id: "total",
        line: 1,
        run: 6,
        label: "Total",
        style: {
          color: "#edf3f6",
          fontSize: 27.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 656.0,
        y: 79.0,
        anchor: "end",
        safeWidth: 170,
        maxCodePoints: 80,
      },
      {
        id: "s0",
        line: 2,
        run: 0,
        label: "Stage 1 label",
        style: {
          color: "#aebfc7",
          fontSize: 10.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 58.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 185,
        maxCodePoints: 80,
      },
      {
        id: "s1",
        line: 2,
        run: 2,
        label: "Stage 2 label",
        style: {
          color: "#aebfc7",
          fontSize: 10.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 281.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 205,
        maxCodePoints: 80,
      },
      {
        id: "s2",
        line: 2,
        run: 4,
        label: "Stage 3 label",
        style: {
          color: "#aebfc7",
          fontSize: 10.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 528.0,
        y: 161.0,
        anchor: "start",
        safeWidth: 155,
        maxCodePoints: 80,
      },
      {
        id: "d0",
        line: 3,
        run: 0,
        label: "Stage 1 duration",
        style: {
          color: "#dce8ee",
          fontSize: 20.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 58.0,
        y: 187.0,
        anchor: "start",
        safeWidth: 185,
        maxCodePoints: 80,
      },
      {
        id: "d1",
        line: 3,
        run: 2,
        label: "Stage 2 duration",
        style: {
          color: "#dce8ee",
          fontSize: 20.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 281.0,
        y: 187.0,
        anchor: "start",
        safeWidth: 205,
        maxCodePoints: 80,
      },
      {
        id: "d2",
        line: 3,
        run: 4,
        label: "Stage 3 duration",
        style: {
          color: "#dce8ee",
          fontSize: 20.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 528.0,
        y: 187.0,
        anchor: "start",
        safeWidth: 155,
        maxCodePoints: 80,
      },
      {
        id: "requestId",
        line: 4,
        run: 0,
        label: "Request id",
        style: {
          color: "#90a2af",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 221.0,
        anchor: "start",
        safeWidth: 340,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 5,
        run: 0,
        label: "Footer",
        style: {
          color: "#90a2af",
          fontSize: 9.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 686.0,
        y: 221.0,
        anchor: "end",
        safeWidth: 300,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "serviceReady",
    profile: "serviceReady/v1",
    name: "Service Passport",
    group: "Useful",
    accent: "#72cbd0",
    background: "#1a222a",
    rows: [1, 3, 1, 5, 5, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#8a9eaa",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 126.0,
        y: 37.0,
        anchor: "start",
        safeWidth: 380,
        maxCodePoints: 80,
      },
      {
        id: "service",
        line: 1,
        run: 0,
        label: "Service",
        style: {
          color: "#f0f5f5",
          fontSize: 33.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 126.0,
        y: 80.0,
        anchor: "start",
        safeWidth: 400,
        maxCodePoints: 48,
      },
      {
        id: "state",
        line: 1,
        run: 2,
        label: "State",
        style: {
          color: "#9de9c8",
          fontSize: 11.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 635.0,
        y: 47.0,
        anchor: "end",
        safeWidth: 60,
        maxCodePoints: 80,
        values: ["READY", "DEGRADED", "OFFLINE", "UNKNOWN"],
      },
      {
        id: "endpoint",
        line: 2,
        run: 0,
        label: "Endpoint",
        style: {
          color: "#5fced1",
          fontSize: 16.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 126.0,
        y: 114.0,
        anchor: "start",
        safeWidth: 550,
        maxCodePoints: 80,
      },
      {
        id: "envLabel",
        line: 3,
        run: 0,
        label: "Env label",
        style: {
          color: "#8a9eaa",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 168.0,
        anchor: "start",
        safeWidth: 210,
        maxCodePoints: 80,
      },
      {
        id: "runtimeLabel",
        line: 3,
        run: 2,
        label: "Runtime label",
        style: {
          color: "#8a9eaa",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 292.0,
        y: 168.0,
        anchor: "start",
        safeWidth: 180,
        maxCodePoints: 80,
      },
      {
        id: "regionLabel",
        line: 3,
        run: 4,
        label: "Region label",
        style: {
          color: "#8a9eaa",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 532.0,
        y: 168.0,
        anchor: "start",
        safeWidth: 154,
        maxCodePoints: 80,
      },
      {
        id: "environment",
        line: 4,
        run: 0,
        label: "Environment",
        style: {
          color: "#e2eaed",
          fontSize: 17.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 192.0,
        anchor: "start",
        safeWidth: 220,
        maxCodePoints: 80,
      },
      {
        id: "runtime",
        line: 4,
        run: 2,
        label: "Runtime",
        style: {
          color: "#e2eaed",
          fontSize: 17.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 292.0,
        y: 192.0,
        anchor: "start",
        safeWidth: 180,
        maxCodePoints: 80,
      },
      {
        id: "region",
        line: 4,
        run: 4,
        label: "Region",
        style: {
          color: "#e2eaed",
          fontSize: 17.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 532.0,
        y: 192.0,
        anchor: "start",
        safeWidth: 154,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 5,
        run: 0,
        label: "Footer",
        style: {
          color: "#8a9eaa",
          fontSize: 9.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 1.0,
        },
        x: 32.0,
        y: 223.0,
        anchor: "start",
        safeWidth: 650,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "commandCard",
    profile: "commandCard/v1",
    name: "Command Card",
    group: "Useful",
    accent: "#67c3c8",
    background: "#1c242a",
    rows: [1, 3, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#8fa1a8",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 32.0,
        y: 33.0,
        anchor: "start",
        safeWidth: 656,
        maxCodePoints: 80,
      },
      {
        id: "step",
        line: 1,
        run: 0,
        label: "Step",
        style: {
          color: "#657780",
          fontSize: 38.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 44.0,
        y: 91.0,
        anchor: "start",
        safeWidth: 56,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 2,
        label: "Title",
        style: {
          color: "#eff3f4",
          fontSize: 29.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 128.0,
        y: 76.0,
        anchor: "start",
        safeWidth: 548,
        maxCodePoints: 48,
      },
      {
        id: "instruction",
        line: 2,
        run: 0,
        label: "Instruction",
        style: {
          color: "#aab9c1",
          fontSize: 14.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 128.0,
        y: 103.0,
        anchor: "start",
        safeWidth: 548,
        maxCodePoints: 80,
      },
      {
        id: "command",
        line: 3,
        run: 0,
        label: "Command",
        style: {
          color: "#dce7e9",
          fontSize: 27.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 73.0,
        y: 167.0,
        anchor: "start",
        safeWidth: 530,
        maxCodePoints: 120,
      },
      {
        id: "safety",
        line: 4,
        run: 0,
        label: "Safety",
        style: {
          color: "#95a8b1",
          fontSize: 11.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 218.0,
        anchor: "start",
        safeWidth: 656,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "releaseBulletin",
    profile: "releaseBulletin/v1",
    name: "Release Bulletin",
    group: "Useful",
    accent: "#3c8574",
    background: "#eeeee4",
    rows: [3, 1, 1, 1, 3],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#64665b",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 32.0,
        y: 33.0,
        anchor: "start",
        safeWidth: 500,
        maxCodePoints: 80,
      },
      {
        id: "version",
        line: 0,
        run: 2,
        label: "Version",
        style: {
          color: "#3b665d",
          fontSize: 12.0,
          fontWeight: 700,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 667.0,
        y: 35.0,
        anchor: "end",
        safeWidth: 72,
        maxCodePoints: 80,
      },
      {
        id: "headline",
        line: 1,
        run: 0,
        label: "Headline",
        style: {
          color: "#26302b",
          fontSize: 36.0,
          fontWeight: 700,
          fontFamily: "serif",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 103.0,
        anchor: "start",
        safeWidth: 656,
        maxCodePoints: 48,
      },
      {
        id: "change0",
        line: 2,
        run: 0,
        label: "First highlight",
        style: {
          color: "#34443b",
          fontSize: 17.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 49.0,
        y: 157.0,
        anchor: "start",
        safeWidth: 270,
        maxCodePoints: 80,
      },
      {
        id: "change1",
        line: 3,
        run: 0,
        label: "Second highlight",
        style: {
          color: "#34443b",
          fontSize: 17.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 349.0,
        y: 157.0,
        anchor: "start",
        safeWidth: 325,
        maxCodePoints: 80,
      },
      {
        id: "channel",
        line: 4,
        run: 0,
        label: "Channel",
        style: {
          color: "#587068",
          fontSize: 12.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 214.0,
        anchor: "start",
        safeWidth: 300,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 4,
        run: 2,
        label: "Footer",
        style: {
          color: "#65736b",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 0.0,
        },
        x: 688.0,
        y: 214.0,
        anchor: "end",
        safeWidth: 340,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "blueprint",
    profile: "blueprint/v1",
    name: "Blueprint",
    group: "Artful",
    accent: "#82c6cc",
    background: "#132b35",
    rows: [1, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#a5c1cc",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 1.5,
        },
        x: 31.0,
        y: 30.0,
        anchor: "start",
        safeWidth: 656,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 0,
        label: "Title",
        style: {
          color: "#e0eff2",
          fontSize: 37.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 247.0,
        y: 107.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 48,
      },
      {
        id: "subtitle",
        line: 2,
        run: 0,
        label: "Subtitle",
        style: {
          color: "#9bbac6",
          fontSize: 14.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 249.0,
        y: 139.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 3,
        run: 0,
        label: "Footer",
        style: {
          color: "#87abb9",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 249.0,
        y: 207.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "contourMap",
    profile: "contourMap/v1",
    name: "Contour Map",
    group: "Artful",
    accent: "#69b7a3",
    background: "#162923",
    rows: [1, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#96aca8",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 32.0,
        y: 32.0,
        anchor: "start",
        safeWidth: 420,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 0,
        label: "Title",
        style: {
          color: "#edf1ea",
          fontSize: 32.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 32.0,
        y: 115.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 48,
      },
      {
        id: "subtitle",
        line: 2,
        run: 0,
        label: "Subtitle",
        style: {
          color: "#a6bcb6",
          fontSize: 16.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 33.0,
        y: 148.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 3,
        run: 0,
        label: "Footer",
        style: {
          color: "#86aaa2",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 32.0,
        y: 215.0,
        anchor: "start",
        safeWidth: 430,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "letterpress",
    profile: "letterpress/v1",
    name: "Letterpress",
    group: "Artful",
    accent: "#43877b",
    background: "#e8e7dc",
    rows: [1, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#78786f",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 36.0,
        y: 34.0,
        anchor: "start",
        safeWidth: 640,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 0,
        label: "Title",
        style: {
          color: "#464842",
          fontSize: 58.0,
          fontWeight: 700,
          fontFamily: "serif",
          letterSpacing: 0.0,
        },
        x: 35.0,
        y: 126.0,
        anchor: "start",
        safeWidth: 650,
        maxCodePoints: 48,
      },
      {
        id: "subtitle",
        line: 2,
        run: 0,
        label: "Subtitle",
        style: {
          color: "#74776c",
          fontSize: 16.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 37.0,
        y: 163.0,
        anchor: "start",
        safeWidth: 640,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 3,
        run: 0,
        label: "Footer",
        style: {
          color: "#70776e",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 37.0,
        y: 216.0,
        anchor: "start",
        safeWidth: 640,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "signalHalftone",
    profile: "signalHalftone/v1",
    name: "Signal Halftone",
    group: "Artful",
    accent: "#ae563b",
    background: "#ede8d8",
    rows: [1, 1, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#777566",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 1.5,
        },
        x: 273.0,
        y: 34.0,
        anchor: "start",
        safeWidth: 410,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 0,
        label: "Title",
        style: {
          color: "#293931",
          fontSize: 41.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 271.0,
        y: 106.0,
        anchor: "start",
        safeWidth: 410,
        maxCodePoints: 48,
      },
      {
        id: "title2",
        line: 2,
        run: 0,
        label: "Title, second line",
        style: {
          color: "#293931",
          fontSize: 41.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 271.0,
        y: 151.0,
        anchor: "start",
        safeWidth: 410,
        maxCodePoints: 48,
      },
      {
        id: "subtitle",
        line: 3,
        run: 0,
        label: "Subtitle",
        style: {
          color: "#626b5d",
          fontSize: 14.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 274.0,
        y: 183.0,
        anchor: "start",
        safeWidth: 410,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 4,
        run: 0,
        label: "Footer",
        style: {
          color: "#737566",
          fontSize: 9.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 274.0,
        y: 218.0,
        anchor: "start",
        safeWidth: 410,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
  {
    id: "orbital",
    profile: "orbital/v1",
    name: "Orbital",
    group: "Artful",
    accent: "#68c9c7",
    background: "#141e28",
    rows: [1, 1, 1, 1],
    slots: [
      {
        id: "eyebrow",
        line: 0,
        run: 0,
        label: "Eyebrow",
        style: {
          color: "#92a1aa",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 1.7,
        },
        x: 264.0,
        y: 34.0,
        anchor: "start",
        safeWidth: 420,
        maxCodePoints: 80,
      },
      {
        id: "title",
        line: 1,
        run: 0,
        label: "Title",
        style: {
          color: "#edf3f3",
          fontSize: 36.0,
          fontWeight: 700,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 262.0,
        y: 111.0,
        anchor: "start",
        safeWidth: 426,
        maxCodePoints: 48,
      },
      {
        id: "subtitle",
        line: 2,
        run: 0,
        label: "Subtitle",
        style: {
          color: "#a5b7c1",
          fontSize: 14.0,
          fontWeight: 400,
          fontFamily: "sans",
          letterSpacing: 0.0,
        },
        x: 264.0,
        y: 146.0,
        anchor: "start",
        safeWidth: 420,
        maxCodePoints: 80,
      },
      {
        id: "footer",
        line: 3,
        run: 0,
        label: "Footer",
        style: {
          color: "#90aab3",
          fontSize: 10.0,
          fontWeight: 400,
          fontFamily: "mono",
          letterSpacing: 2.0,
        },
        x: 264.0,
        y: 215.0,
        anchor: "start",
        safeWidth: 420,
        maxCodePoints: 80,
      },
    ],
    renderers: ["svg", "text"],
    editableStyleKeys: ["color"],
  },
];
const statuses: Partial<Record<CardPresetId, PresentationStatus>> = {
  buildReceipt: {
    slot: "outcome",
    source: "text",
    palettes: {
      PASSED: {
        background: "#d9e9db",
        stroke: "#a9c7b2",
        marker: "#27775c",
        ink: "#156751",
      },
      FAILED: {
        background: "#f6dedd",
        stroke: "#d8aaa8",
        marker: "#913d38",
        ink: "#913d38",
      },
      WARNING: {
        background: "#f1e7c5",
        stroke: "#cfbc82",
        marker: "#806018",
        ink: "#806018",
      },
      UNKNOWN: {
        background: "#dfe4e3",
        stroke: "#aab7b3",
        marker: "#4b605a",
        ink: "#4b605a",
      },
    },
  },
  serviceReady: {
    slot: "state",
    source: "text",
    palettes: {
      READY: {
        background: "#213a34",
        stroke: "none",
        marker: "#83cca7",
        ink: "#9de9c8",
      },
      DEGRADED: {
        background: "#463e28",
        stroke: "none",
        marker: "#edcd84",
        ink: "#edcd84",
      },
      OFFLINE: {
        background: "#462d30",
        stroke: "none",
        marker: "#f1acaa",
        ink: "#f1acaa",
      },
      UNKNOWN: {
        background: "#30404a",
        stroke: "none",
        marker: "#cad6de",
        ink: "#cad6de",
      },
    },
  },
  requestTrace: {
    slot: "status",
    source: "tone",
    palettes: {
      success: {
        background: "#233c34",
        stroke: "none",
        marker: "#b8e1cd",
        ink: "#b8e1cd",
      },
      warning: {
        background: "#463e28",
        stroke: "none",
        marker: "#edcd84",
        ink: "#edcd84",
      },
      error: {
        background: "#462d30",
        stroke: "none",
        marker: "#f1acaa",
        ink: "#f1acaa",
      },
      neutral: {
        background: "#30404a",
        stroke: "none",
        marker: "#cad6de",
        ink: "#cad6de",
      },
    },
  },
};
const accents: Record<CardPresetId, readonly string[]> = {
  buildReceipt: ["Receipt spine"],
  requestTrace: ["Ordered stage nodes"],
  serviceReady: ["Passport glyph"],
  commandCard: ["Command chevron"],
  releaseBulletin: ["Editorial underline"],
  blueprint: ["Cube edges"],
  contourMap: ["Highlighted contour"],
  letterpress: ["Paper underline"],
  signalHalftone: ["Halftone ink"],
  orbital: ["Orbit highlight"],
};
const descriptors: readonly PresentationDescriptor[] = deepFreeze(
  definitions.map((d) => {
    const status = statuses[d.id];
    return {
      ...d,
      accentGeometry: accents[d.id],
      slots: d.slots.map((s) =>
        status?.slot === s.id ? { ...s, editableStyleKeys: [] } : s,
      ),
      ...(status ? { status } : {}),
      parameters: {
        accent: { type: "color" as const, default: d.accent },
        detail: {
          type: "enum" as const,
          default: "standard",
          values: ["minimal", "standard"],
        },
        ...(d.id === "requestTrace"
          ? {
              tone: {
                type: "enum" as const,
                default: "neutral",
                values: ["success", "warning", "error", "neutral"],
              },
            }
          : {}),
      },
    };
  }),
);
export const SEPARATOR_STYLE: TextStyle = deepFreeze({
  color: "#000000",
  fontSize: 8,
  fontWeight: 400,
  fontFamily: "mono",
  letterSpacing: 0,
});
export function getPresentationDescriptors(): readonly PresentationDescriptor[] {
  return descriptors;
}
export function presentationDescriptor(
  profile: string,
): PresentationDescriptor | undefined {
  return descriptors.find((d) => d.profile === profile);
}
